pretrain: "./exp/clip_ucf/ViT-B/16/breakfast_acti/last_model.pt"
resume:
seed: 1024
data:
    dataset: breakfast_acti_ls
    modality: RGB
    num_frames: 16
    ds: 4
    ol: 2
    seg_length: 1
    n_split: 5
    split: 2
    batch_size: 12
    workers: 32
    gpus: 4
    num_classes: 10
    index_bias: 1
    input_size: 224
    max_act: 6
    randaug:
        N: 0 #2
        M: 0  #9
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True # scratch, imagenet, kinetics
    drop_out: 0.0 # probability of an element to be zeroed
    emb_dropout: 0.0 # probability of embedding to be zeroed
    partial_bn: False
    version: ''
    bn_momentum: 0.1
    consensus_type: avg
    type: clip_ucf
    sim_header: 'Transf'  #Transf   meanP   LSTM   Transf_cls Conv_1D
    fix_text: False
    fix_img: False
    describe:
solver:
    type: cosine
    epochs: 100
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: False
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1